---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vaultXXXX.yml

  tasks:

  - name: Incorrect names jobs templates
    ansible.builtin.fail:
      msg: "There was not included job_template in a workflow, what a genius"
    when: tower_workflow_job_name is undefined
    
  - name: Sending message
    ansible.builtin.uri:
      url: "https://api.telegram.org/bot{{ tokenBot }}/sendmessage?chat_id={{ gymkanaGroups[team_name]['chatID'] }}&parse_mode=HTML&text={{ gymkanaGroups[team_name]['msgVar'] | urlencode }}"
    when: checks_steps0 and checks_steps1
