---
- hosts: localhost
  connection: local 
  gather_facts: no

  tasks:


  - debug: 
      msg: "{{checks_steps0}}"


  - debug: 
      msg: "{{checks_steps1}}"


  - debug: 
      msg: "Correcto"
    when: checks_steps0 and checks_steps1
      
