---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vaultXXXX.yml

  tasks:

  - name: Check job_template execute in workflow
    ansible.builtin.fail:
      msg: "SECURE RULE VIOLATE::This job_template is only execute in a workflow"
    when: awx_workflow_job_name is undefined
    
  - name: Sending message to telegram to get OC acces
    ansible.builtin.uri:
      url: "https://api.telegram.org/bot{{ tokenBot }}/sendmessage?chat_id={{ gymkanaGroups[team_name]['chatID'] }}&parse_mode=HTML&text={{ gymkanaGroups[team_name]['msgVar'] | urlencode }}"
    when: checks_steps_V == messages.checks.estructure and checks_steps_W == messages.checks.vars
