---
- hosts: localhost
  connection: local 
  gather_facts: no

  tasks:

  

  - debug: 
      msg: "{{output.assets.workflow_job_templates[0].related.workflow_nodes}}"
    when: checks_steps0 and checks_steps1
      
