---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vaultXXXX.yml
  environment:
    CONTROLLER_HOST: "{{vault_file_vars.connection_aap.CONTROLLER_HOST}}"
    CONTROLLER_USERNAME: "{{vault_file_vars.connection_aap.CONTROLLER_USERNAME}}"
    CONTROLLER_PASSWORD: "{{vault_file_vars.connection_aap.CONTROLLER_PASSWORD}}"
    CONTROLLER_VERIFY_SSL: "{{vault_file_vars.connection_aap.CONTROLLER_VERIFY_SSL}}"

  tasks:

  - name: Get info job_template execute
    ansible.controller.export:
      validate_certs: no
      all: false
      job_templates: "{{tower_job_template_name}}"
    register: output_job_template_info

  - name: Incorrect name job_template
    vars:
      organization_name: "{{ output_job_template_info.assets.job_templates[0].natural_key.organization.name }}"
    ansible.builtin.fail:
      msg: "SECURE RULE VIOLATE::The name of job_template is not valid"
    when: awx_job_template_name != organization_name+" "+vault_file_vars.step_name

  - name: Check job_template execute in workflow
    ansible.builtin.fail:
      msg: "SECURE RULE VIOLATE::This job_template is only execute in a workflow"
    when: awx_workflow_job_name is undefined
    
  - name: Sending message to telegram to get OC acces
    debug:
      msg: "no tocar la url es caca:::https://api.telegram.org/bot{{ vault_file_vars.tokenBot }}/sendmessage?chat_id={{ vault_file_vars.gymkanaGroups[team_name]['chatID'] }}&parse_mode=HTML&text={{ vault_file_vars.gymkanaGroups.msgVar | urlencode }}"
    when: checks_steps_V == vault_file_vars.messages.checks.estructure and checks_steps_W == vault_file_vars.messages.checks.vars
