---
- hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
    
  - name: hostvars
    debug:
      var: "hostvars"

  - name: Incorrect var
    ansible.builtin.fail:
      msg: "Incorrect var value, what a genius"
    when: not_work != "work"
    no_log: "{{var_logs}}"

  - name: Oki checks 1
    ansible.builtin.set_stats:
      data:
        checks_steps1: true