---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vaultYYYY.yml

  tasks:

  - name: Check job_template execute in workflow
    ansible.builtin.fail:
      msg: "SECURE RULE VIOLATE::This job_template is only execute in a workflow"
    when: awx_workflow_job_name is undefined

  - name: Incorrect var
    ansible.builtin.fail:
      msg: "SECURE RULE VIOLATE::Value not_work is incorrect value is {{work_message}}, this protocol is to check permison to add vars and show execution logs"
    when: not_work | default("") != work_message
    no_log: "{{var_logs | default(true)}}"

  - name: Oki checks 1
    ansible.builtin.set_stats:
      data:
        checks_steps_W: "{{messages.checks.vars}}"
