---
- hosts: localhost
  connection: local 
  gather_facts: no

  tasks:

  - name: Incorrect var
    ansible.builtin.fail:
      msg: "Incorrect var value, what a genius"
    when: no_funciona != "si funciona"
    no_log: var_logs

  - name: Oki checks 1
    ansible.builtin.set_stats:
      checks_steps1: true