---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vaultYYYY.yml

  tasks:

  - name: Incorrect names jobs templates
    ansible.builtin.fail:
      msg: "There was not included job_template in a workflow, what a genius"
    when: tower_workflow_job_name is undefined

  - name: Incorrect var
    ansible.builtin.fail:
      msg: "Incorrect var value, what a genius :: value is {{work_message}}"
    when: not_work | default("") != work_message
    no_log: "{{var_logs | default(true)}}"

  - name: Oki checks 1
    ansible.builtin.set_stats:
      data:
        checks_steps_W: "{{messages.checks.vars}}"
