---
- hosts: localhost
  connection: local 
  gather_facts: no
  environment:
     CONTROLLER_HOST: https://192.168.0.150
     CONTROLLER_USERNAME: admin
     CONTROLLER_PASSWORD: redhat00
     CONTROLLER_VERIFY_SSL: False
  tasks:

  - debug: 
      msg: "{{tower_job_template_name}}"

  - debug: 
      msg: "{{tower_job_template_id}}"

  - debug: 
      msg: "{{tower_workflow_job_name}}"

  - debug: 
      msg: "{{tower_workflow_job_id}}"

  - name: Get info job_template execute
    ansible.controller.export:
      validate_certs: no
      all: false
      job_templates: "{{tower_job_template_name}}"
    register: output

  - debug: 
      msg: "{{output}}"

  - debug: 
      msg: "{{output.job_templates[0].natural_key.organization.name}}"

  - name: Get info workflow_job execute
    ansible.controller.export:
      validate_certs: no
      all: false
      workflow_job_templates: "{{tower_workflow_job_name}}"
    register: output

  - debug: 
      msg: "{{output}}"

  - debug: 
      msg: "{{output.workflow_job_templates[0].organization}}"

  - debug: 
      msg: "{{output.workflow_job_templates[0].related.workflow_nodes}}"

  - name: Incorrect name Workflow
    ansible.builtin.fail:
      msg: "There was no better name for the workflow, what a genius ::: '{{tower_workflow_job_name}}'"
    when: tower_workflow_job_name != "Workflow to validate {{output.job_templates[0].natural_key.organization.name}}"

  - name: Incorrect order job_templates in workflow
    ansible.builtin.fail:
      msg: "There was no better create workflow without organization, what a genius"
    # when: item
    loop: output.workflow_job_templates[0].related.workflow_nodes

  - name: Incorrect name job template
    ansible.builtin.fail:
      msg: "There was no better create workflow without organization, what a genius"
    # when: item
    loop: output.workflow_job_templates[0].related.workflow_nodes

