---
- hosts: localhost
  connection: local 
  gather_facts: no
  environment:
     CONTROLLER_HOST: https://192.168.0.150
     CONTROLLER_USERNAME: admin
     CONTROLLER_PASSWORD: redhat00
     CONTROLLER_VERIFY_SSL: False
  tasks:

  - debug: 
      msg: "{{tower_job_template_name}}"

  - debug: 
      msg: "{{tower_job_template_id}}"

  - debug: 
      msg: "{{tower_workflow_job_name}}"

  - debug: 
      msg: "{{tower_workflow_job_id}}"

  - ansible.controller.export:
      validate_certs: no
      all: true
      job_templates: "tower_job_template_name"
    register: output

  - debug: 
      msg: "{{output}}"

  - ansible.controller.export:
      validate_certs: no
      all: true
      workflow_job_templates: "tower_workflow_job_name"
    register: output

  - debug: 
      msg: "{{output}}"

  - name: Incorrect name Workflow
    ansible.builtin.fail:
      msg: "There was no better name for the workflow, what a genius ::: '{{tower_workflow_job_name}}'"
    when: tower_workflow_job_name != "Workflow_to_validate"